BlogWarpUp/Front/Models/ErrorViewModel.cs
using System;

namespace Front.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogWarpUp/Front/Controllers/HomeController.cs
using Back.model;
using Front.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;


namespace Front.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        { 
            //C: \Users\Blackhorde\source\repos\BlogWarpUp
            var httpClient = new HttpClient();
            var json =await httpClient.GetStringAsync("http://localhost:8081/api/posteo");
            List<Post> posts = JsonConvert.DeserializeObject<List<Post>>(json);

            return View(posts);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogWarpUp/Front/Controllers/PostController.cs
using Back.model;
using System.Net;
using Front.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Front.Controllers
{
    public class PostController : Controller
    {
        string url = "http://localhost:8081/api/posteo";
        public async Task<IActionResult> ListPosts()
        {
            //C: \Users\Blackhorde\source\repos\BlogWarpUp
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync(url );
            List<Post> posts = JsonConvert.DeserializeObject<List<Post>>(json);
            return View(posts);
        }
        [HttpGet]
        public ActionResult AddPost()
        {
            Post p = new Post();
            p.FechaCreacion = DateTime.Now;
            return View(p);
        }

        [HttpPost]
        public async Task<ActionResult> AddPost(Post p)
        {
            p.Activo = true;
            var httpClient = new HttpClient();
            var data = System.Text.Json.JsonSerializer.Serialize(p);
            HttpContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
            var httpResponse = await httpClient.PostAsync(url, content);
            
            if (httpResponse.IsSuccessStatusCode)
            {
                var result = await httpResponse.Content.ReadAsStringAsync();
            }

            var json = await httpClient.GetStringAsync(url);
            List<Post> posts = JsonConvert.DeserializeObject<List<Post>>(json);
            return View("ListPosts", posts);
        }

        public async Task<ActionResult> EditPost(int id)
        {
            var httpClient = new HttpClient();
            string url2 = "http://localhost:8081/api/posteo/" + id;
            var json = await httpClient.GetStringAsync(url2);
            Post posts = JsonConvert.DeserializeObject<Post>(json);
            return View(posts);

        }
        [HttpPost]
        public async Task<ActionResult> EditPost(Post p)
        {
            int id = p.Id;
            p.Activo = true;
            string url2 = "http://localhost:8081/api/posteo/" + id;
            var httpClient = new HttpClient();
            var data = JsonConvert.SerializeObject(p);

            HttpContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
            var httpResponse = await httpClient.PatchAsync(url2, content);

            if (httpResponse.IsSuccessStatusCode)
            {
                var result = await httpResponse.Content.ReadAsStringAsync();
            }

            var json = await httpClient.GetStringAsync(url);
            List<Post> posts = JsonConvert.DeserializeObject<List<Post>>(json);
            return View("ListPosts", posts);

        }
        public async Task<ActionResult> Delete(int id)
        {
            var httpClient = new HttpClient();
            string url2 = "http://localhost:8081/api/posteo/" + id;
            var httpResponse = await httpClient.DeleteAsync(url2);
            if (httpResponse.IsSuccessStatusCode)
            {
                var result = await httpResponse.Content.ReadAsStringAsync();
            }
            var json2 = await httpClient.GetStringAsync(url);
            List<Post> posts = JsonConvert.DeserializeObject<List<Post>>(json2);
            return View("ListPosts" ,posts);
        }

        public async Task<ActionResult> View(int id)
        {
            var httpClient = new HttpClient();
            string url2 = "http://localhost:8081/api/posteo/" + id;
            var json = await httpClient.GetStringAsync(url2);
            Post posts = JsonConvert.DeserializeObject<Post>(json);
            return View(posts);
        }
    }
}

BlogWarpUp/Front/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Listado de posts</h1>
    <table class="table-bordered table">
        <tr>
            <th>Title</th>
            <th>Action</th>
        </tr>
        @foreach (var post in Model)
        {
            <tr>
                <td>@post.Titulo</td>
                <td>
                    <input onclick="document.location.href='@Url.Content("~/Home/Edit/"+post.Id)'" type="button" value="Edit" class="btn btn-dark">
                    <input onclick="document.location.href='@Url.Content("~/Home/Delete/"+post.Id)'" type="button" value="Delete" class="btn btn-dark">

                </td>
            </tr>
        }
    </table>
</div>

BlogWarpUp/Front/Views/Post/AddPost.cshtml
@model Back.model.Post
<div>
    <div class="col-md-2"></div>
    <div class="col-md=8">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>Titulo</label>
                @Html.TextBoxFor(x => x.Titulo, htmlAttributes: new { @class = "form-control", @required = "required" })
            </div>
            <div class="form-group">
                <label>Contenido</label>
                @Html.TextAreaFor(x => x.Contenido, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Imagen</label>
                @Html.TextBoxFor(x => x.Urlimagen, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Categoria</label>
                @Html.DropDownListFor(x => x.Categoria, new List<SelectListItem>
                    {
                       new SelectListItem{ Text="Politica", Value = "1" },
                       new SelectListItem{ Text="Economia", Value = "2" },
                       new SelectListItem{ Text="Local", Value = "3" },
                    }, new { @class = "form-control" } )
            </div>
            <div class="form-group">
                <label>Fecha</label>
                @Html.TextBoxFor(x => x.FechaCreacion, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            </div>
            <input type="file" />
            <div>

            </div>

            <input type="submit" value="Cargar" class="btn btn-primary" />

        }
    </div>
    <div class="col-md-2"></div>
</div>

BlogWarpUp/Front/Views/Post/EditPost.cshtml
@model Back.model.Post
<div>
    <div class="col-md-2"></div>
    <div class="col-md=8">
        @using (Html.BeginForm())
        {
            <div>
                <label>ID</label>
                @Html.TextBoxFor(x => x.Id, htmlAttributes: new {@class = "form-control", @disable = "disable", @readonly="readonly" })
            </div>
            <div class="form-group">
                <label>Titulo</label>
                @Html.TextBoxFor(x => x.Titulo, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Contenido</label>
                @Html.TextAreaFor(x => x.Contenido, htmlAttributes: new { @class = "form-control" })
            </div>
            <input type="submit" value="Modificar" class="btn btn-primary" />

        }
    </div>
    <div class="col-md-2"></div>
</div>

BlogWarpUp/Front/Views/Post/ListPosts.cshtml
<div class="text-center">
        <h1 class="display-4">Listado de posts</h1>
        <table class="table-bordered table">
            <tr>
                <th>Title</th>
                <th>Action</th>
            </tr>
            @foreach (var post in Model)
            {
                <tr>
                    <td>@post.Titulo</td>
                    <td>
                        <input onclick="document.location.href='@Url.Content("~/Post/EditPost/"+post.Id)'" type="button" value="Edit" class="btn btn-dark">
                        <input onclick="document.location.href='@Url.Content("~/Post/Delete/"+post.Id)'" type="button" value="Delete" class="btn btn-dark">
                        <input onclick="document.location.href='@Url.Content("~/Post/View/"+post.Id)'" type="button" value="View" class="btn btn-dark">
                    </td>
                </tr>
            }
        </table>
    </div>

BlogWarpUp/Front/Views/Post/View.cshtml
@model Back.model.Post
<div>
    <div class="col-md-2"></div>
    <div class="col-md=8">
        @using (Html.BeginForm())
        {
            <div>
                <label>ID</label>
                @Html.TextBoxFor(x => x.Id, htmlAttributes: new { @class = "form-control", @disable = "disable", @readonly = "readonly" })
            </div>
            <div class="form-group">
                <label>Titulo</label>
                @Html.TextBoxFor(x => x.Titulo, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="form-group">
                <label>Contenido</label>
                @Html.TextAreaFor(x => x.Contenido, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="form-group">
                <label>Fecha</label>
                @Html.TextBoxFor(x => x.FechaCreacion, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", @readonly="readonly"})
            </div>
            <input type="submit" value="Modificar" class="btn btn-primary" />

        }
    </div>
    <div class="col-md-2"></div>
</div>

BlogWarpUp/Front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Front</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="AddPost">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="ListPosts">List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Front - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>